version: '3.7'
services: 
   
    eureka-server:
        image: lionelsamrat10/eureka-server:0.1
        ports: 
            - "8761:8761"
        restart: always
       
        networks:
            - app-network
    
    truyum:
        image: lionelsamrat10/truyum:0.1
        ports: 
            - "8085:8085"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
                
        depends_on:
            - eureka-server
        networks:
            - app-network
 
    zuul-gateway:
        image: lionelsamrat10/zuul-gateway:0.1
        ports: 
            - "8083:8083"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
        
        depends_on:
            - eureka-server
        networks:
            - app-network
 
# Networks to be created to facilitate communication between containers
networks:
    app-network:  